@startuml
class com.kenkogroup.kenko.recipe.entity.edamam.P__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ P__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ P__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ P__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ P__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fibtg {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fibtg withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fibtg withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fibtg withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fibtg withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Procnt {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Procnt withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Procnt withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Procnt withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Procnt withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Chole {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Chole withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Chole withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Chole withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Chole withAdditionalProperty(String,Object)
+ String toString()
}
interface com.kenkogroup.kenko.recipe.service.RecipeService {
~ double CaloriesCalculator(String,String,String,String)
}
class com.kenkogroup.kenko.recipe.entity.edamam.TotalDaily {
- EnercKcal__1 enercKcal
- Fat__1 fat
- Fasat__1 fasat
- Chocdf__1 chocdf
- Fibtg__1 fibtg
- Procnt__1 procnt
- Chole__1 chole
- Na__1 na
- Ca__1 ca
- Mg__1 mg
- K__1 k
- Fe__1 fe
- Zn__1 zn
- P__1 p
- VitaRae__1 vitaRae
- Vitc__1 vitc
- Thia__1 thia
- Ribf__1 ribf
- Nia__1 nia
- Vitb6a__1 vitb6a
- Foldfe__1 foldfe
- Vitb12__1 vitb12
- Vitd__1 vitd
- Tocpha__1 tocpha
- Vitk1__1 vitk1
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ EnercKcal__1 getEnercKcal()
+ void setEnercKcal(EnercKcal__1)
+ TotalDaily withEnercKcal(EnercKcal__1)
+ Fat__1 getFat()
+ void setFat(Fat__1)
+ TotalDaily withFat(Fat__1)
+ Fasat__1 getFasat()
+ void setFasat(Fasat__1)
+ TotalDaily withFasat(Fasat__1)
+ Chocdf__1 getChocdf()
+ void setChocdf(Chocdf__1)
+ TotalDaily withChocdf(Chocdf__1)
+ Fibtg__1 getFibtg()
+ void setFibtg(Fibtg__1)
+ TotalDaily withFibtg(Fibtg__1)
+ Procnt__1 getProcnt()
+ void setProcnt(Procnt__1)
+ TotalDaily withProcnt(Procnt__1)
+ Chole__1 getChole()
+ void setChole(Chole__1)
+ TotalDaily withChole(Chole__1)
+ Na__1 getNa()
+ void setNa(Na__1)
+ TotalDaily withNa(Na__1)
+ Ca__1 getCa()
+ void setCa(Ca__1)
+ TotalDaily withCa(Ca__1)
+ Mg__1 getMg()
+ void setMg(Mg__1)
+ TotalDaily withMg(Mg__1)
+ K__1 getK()
+ void setK(K__1)
+ TotalDaily withK(K__1)
+ Fe__1 getFe()
+ void setFe(Fe__1)
+ TotalDaily withFe(Fe__1)
+ Zn__1 getZn()
+ void setZn(Zn__1)
+ TotalDaily withZn(Zn__1)
+ P__1 getP()
+ void setP(P__1)
+ TotalDaily withP(P__1)
+ VitaRae__1 getVitaRae()
+ void setVitaRae(VitaRae__1)
+ TotalDaily withVitaRae(VitaRae__1)
+ Vitc__1 getVitc()
+ void setVitc(Vitc__1)
+ TotalDaily withVitc(Vitc__1)
+ Thia__1 getThia()
+ void setThia(Thia__1)
+ TotalDaily withThia(Thia__1)
+ Ribf__1 getRibf()
+ void setRibf(Ribf__1)
+ TotalDaily withRibf(Ribf__1)
+ Nia__1 getNia()
+ void setNia(Nia__1)
+ TotalDaily withNia(Nia__1)
+ Vitb6a__1 getVitb6a()
+ void setVitb6a(Vitb6a__1)
+ TotalDaily withVitb6a(Vitb6a__1)
+ Foldfe__1 getFoldfe()
+ void setFoldfe(Foldfe__1)
+ TotalDaily withFoldfe(Foldfe__1)
+ Vitb12__1 getVitb12()
+ void setVitb12(Vitb12__1)
+ TotalDaily withVitb12(Vitb12__1)
+ Vitd__1 getVitd()
+ void setVitd(Vitd__1)
+ TotalDaily withVitd(Vitd__1)
+ Tocpha__1 getTocpha()
+ void setTocpha(Tocpha__1)
+ TotalDaily withTocpha(Tocpha__1)
+ Vitk1__1 getVitk1()
+ void setVitk1(Vitk1__1)
+ TotalDaily withVitk1(Vitk1__1)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ TotalDaily withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Nia__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Nia__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Nia__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Nia__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Nia__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.K {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ K withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ K withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ K withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ K withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fams {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fams withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fams withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fams withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fams withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Tocpha__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Tocpha__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Tocpha__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Tocpha__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Tocpha__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.EnercKcal__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ EnercKcal__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ EnercKcal__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ EnercKcal__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ EnercKcal__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Na {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Na withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Na withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Na withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Na withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.impl.RecipeServiceImpl {
+ double CaloriesCalculator(String,String,String,String)
}
class com.kenkogroup.kenko.recipe.entity.edamam.VitaRae {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ VitaRae withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ VitaRae withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ VitaRae withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ VitaRae withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitb6a {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitb6a withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitb6a withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitb6a withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitb6a withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fasat__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fasat__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fasat__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fasat__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fasat__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.SugarAlcohol {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ SugarAlcohol withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ SugarAlcohol withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ SugarAlcohol withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ SugarAlcohol withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.TotalNutrients {
- EnercKcal enercKcal
- Fat fat
- Fasat fasat
- Fatrn fatrn
- Fams fams
- Fapu fapu
- Chocdf chocdf
- CHOCDFNet cHOCDFNet
- Fibtg fibtg
- Sugar sugar
- SUGARAdded sUGARAdded
- Procnt procnt
- Chole chole
- Na na
- Ca ca
- Mg mg
- K k
- Fe fe
- Zn zn
- P p
- VitaRae vitaRae
- Vitc vitc
- Thia thia
- Ribf ribf
- Nia nia
- Vitb6a vitb6a
- Foldfe foldfe
- Folfd folfd
- Folac folac
- Vitb12 vitb12
- Vitd vitd
- Tocpha tocpha
- Vitk1 vitk1
- SugarAlcohol sugarAlcohol
- Water water
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ EnercKcal getEnercKcal()
+ void setEnercKcal(EnercKcal)
+ TotalNutrients withEnercKcal(EnercKcal)
+ Fat getFat()
+ void setFat(Fat)
+ TotalNutrients withFat(Fat)
+ Fasat getFasat()
+ void setFasat(Fasat)
+ TotalNutrients withFasat(Fasat)
+ Fatrn getFatrn()
+ void setFatrn(Fatrn)
+ TotalNutrients withFatrn(Fatrn)
+ Fams getFams()
+ void setFams(Fams)
+ TotalNutrients withFams(Fams)
+ Fapu getFapu()
+ void setFapu(Fapu)
+ TotalNutrients withFapu(Fapu)
+ Chocdf getChocdf()
+ void setChocdf(Chocdf)
+ TotalNutrients withChocdf(Chocdf)
+ CHOCDFNet getCHOCDFNet()
+ void setCHOCDFNet(CHOCDFNet)
+ TotalNutrients withCHOCDFNet(CHOCDFNet)
+ Fibtg getFibtg()
+ void setFibtg(Fibtg)
+ TotalNutrients withFibtg(Fibtg)
+ Sugar getSugar()
+ void setSugar(Sugar)
+ TotalNutrients withSugar(Sugar)
+ SUGARAdded getSUGARAdded()
+ void setSUGARAdded(SUGARAdded)
+ TotalNutrients withSUGARAdded(SUGARAdded)
+ Procnt getProcnt()
+ void setProcnt(Procnt)
+ TotalNutrients withProcnt(Procnt)
+ Chole getChole()
+ void setChole(Chole)
+ TotalNutrients withChole(Chole)
+ Na getNa()
+ void setNa(Na)
+ TotalNutrients withNa(Na)
+ Ca getCa()
+ void setCa(Ca)
+ TotalNutrients withCa(Ca)
+ Mg getMg()
+ void setMg(Mg)
+ TotalNutrients withMg(Mg)
+ K getK()
+ void setK(K)
+ TotalNutrients withK(K)
+ Fe getFe()
+ void setFe(Fe)
+ TotalNutrients withFe(Fe)
+ Zn getZn()
+ void setZn(Zn)
+ TotalNutrients withZn(Zn)
+ P getP()
+ void setP(P)
+ TotalNutrients withP(P)
+ VitaRae getVitaRae()
+ void setVitaRae(VitaRae)
+ TotalNutrients withVitaRae(VitaRae)
+ Vitc getVitc()
+ void setVitc(Vitc)
+ TotalNutrients withVitc(Vitc)
+ Thia getThia()
+ void setThia(Thia)
+ TotalNutrients withThia(Thia)
+ Ribf getRibf()
+ void setRibf(Ribf)
+ TotalNutrients withRibf(Ribf)
+ Nia getNia()
+ void setNia(Nia)
+ TotalNutrients withNia(Nia)
+ Vitb6a getVitb6a()
+ void setVitb6a(Vitb6a)
+ TotalNutrients withVitb6a(Vitb6a)
+ Foldfe getFoldfe()
+ void setFoldfe(Foldfe)
+ TotalNutrients withFoldfe(Foldfe)
+ Folfd getFolfd()
+ void setFolfd(Folfd)
+ TotalNutrients withFolfd(Folfd)
+ Folac getFolac()
+ void setFolac(Folac)
+ TotalNutrients withFolac(Folac)
+ Vitb12 getVitb12()
+ void setVitb12(Vitb12)
+ TotalNutrients withVitb12(Vitb12)
+ Vitd getVitd()
+ void setVitd(Vitd)
+ TotalNutrients withVitd(Vitd)
+ Tocpha getTocpha()
+ void setTocpha(Tocpha)
+ TotalNutrients withTocpha(Tocpha)
+ Vitk1 getVitk1()
+ void setVitk1(Vitk1)
+ TotalNutrients withVitk1(Vitk1)
+ SugarAlcohol getSugarAlcohol()
+ void setSugarAlcohol(SugarAlcohol)
+ TotalNutrients withSugarAlcohol(SugarAlcohol)
+ Water getWater()
+ void setWater(Water)
+ TotalNutrients withWater(Water)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ TotalNutrients withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipePersonalized.controller.RecipePersoController {
- List<RecipePersonalized> recipes
- RecipePersoService recipePersoService
+ void addRecipe(RecipePersonalized)
+ void updateRecipe(int,RecipePersonalized)
+ void deleteRecipe(int)
+ List<String> analyseRecipe(RecipePersonalized)
+ List<String> conversion(List<QuantityCat>)
+ List<RecipePersonalized> getRecipes()
+ List<String> analyseRecipes()
}
enum com.kenkogroup.kenko.category.entity.Other {
+  CHEESE
+  EGG
+  BREAD
- String name
+ String analyse(Double)
}
interface com.kenkogroup.kenko.registration.Repo.UserRepo {
}
class com.kenkogroup.kenko.recipe.entity.edamam.Chocdf {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Chocdf withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Chocdf withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Chocdf withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Chocdf withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fapu {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fapu withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fapu withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fapu withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fapu withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitb6a__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitb6a__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitb6a__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitb6a__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitb6a__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.Quantity.QuantityCat {
- String category
- double percentage
+ String getCategory()
+ double getPercentage()
+ void setCategory(String)
+ void setPercentage(double)
}
class com.kenkogroup.kenko.recipe.entity.edamam.Mg {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Mg withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Mg withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Mg withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Mg withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.CHOCDFNet {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ CHOCDFNet withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ CHOCDFNet withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ CHOCDFNet withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ CHOCDFNet withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitd__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitd__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitd__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitd__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitd__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Thia {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Thia withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Thia withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Thia withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Thia withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.controller.RecipeController {
~ Random random
~ List<String> ingredients
~ List<String> type
~ RecipeService recipeService
- RecipeEdamam apiCall(String)
+ List<RecipeEdamam> getRecettes(String)
+ List<RecipeEdamam> getRecettesWithNumberOfRecipeWithDuration(String,String,String)
+ List<RecipeEdamam> getRecipeWithCalories(String,String,String,String,String)
+ List<RecipeEdamam> getMenu()
}
enum com.kenkogroup.kenko.category.entity.Vegetable {
+  TOMATO
+  POTATO
+  CARROT
+  GARLIC
+  EGGPLANT
+  ONION
+  PEPPER
+  SPINACH
+  PEA
+  CELERY
+  CORN
+  BROCOLI
- String name
+ String analyse(Double)
}
class com.kenkogroup.kenko.recipe.entity.edamam.Water {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Water withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Water withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Water withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Water withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.KenkoApplication {
+ {static} void main(String[])
}
class com.kenkogroup.kenko.recipe.entity.edamam.Thia__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Thia__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Thia__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Thia__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Thia__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fatrn {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fatrn withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fatrn withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fatrn withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fatrn withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.registration.Service.impl.UserIMPL {
- UserRepo userRepo
+ String addUser(UserDTO)
}
class com.kenkogroup.kenko.recipe.entity.edamam.Foldfe {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Foldfe withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Foldfe withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Foldfe withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Foldfe withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Chocdf__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Chocdf__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Chocdf__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Chocdf__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Chocdf__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Ribf {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Ribf withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Ribf withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Ribf withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Ribf withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.SUGARAdded {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ SUGARAdded withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ SUGARAdded withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ SUGARAdded withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ SUGARAdded withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitk1__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitk1__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitk1__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitk1__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitk1__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Ribf__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Ribf__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Ribf__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Ribf__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Ribf__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Ca__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Ca__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Ca__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Ca__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Ca__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitc {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitc withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitc withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitc withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitc withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.P {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ P withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ P withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ P withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ P withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.RecipeEdamam {
- String uri
- String label
- String image
- String source
- String url
- String shareAs
- double yield
- List<String> dietLabels
- List<String> healthLabels
- List<String> cautions
- List<String> ingredientLines
- List<Ingredient> ingredients
- double calories
- double totalWeight
- double totalTime
- List<String> cuisineType
- List<String> mealType
- List<String> dishType
- TotalNutrients totalNutrients
- TotalDaily totalDaily
- List<Digest> digest
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getUri()
+ void setUri(String)
+ RecipeEdamam withUri(String)
+ String getLabel()
+ void setLabel(String)
+ RecipeEdamam withLabel(String)
+ String getImage()
+ void setImage(String)
+ RecipeEdamam withImage(String)
+ String getSource()
+ void setSource(String)
+ RecipeEdamam withSource(String)
+ String getUrl()
+ void setUrl(String)
+ RecipeEdamam withUrl(String)
+ String getShareAs()
+ void setShareAs(String)
+ RecipeEdamam withShareAs(String)
+ double getYield()
+ void setYield(double)
+ RecipeEdamam withYield(double)
+ List<String> getDietLabels()
+ void setDietLabels(List<String>)
+ RecipeEdamam withDietLabels(List<String>)
+ List<String> getHealthLabels()
+ void setHealthLabels(List<String>)
+ RecipeEdamam withHealthLabels(List<String>)
+ List<String> getCautions()
+ void setCautions(List<String>)
+ RecipeEdamam withCautions(List<String>)
+ List<String> getIngredientLines()
+ void setIngredientLines(List<String>)
+ RecipeEdamam withIngredientLines(List<String>)
+ List<Ingredient> getIngredients()
+ void setIngredients(List<Ingredient>)
+ RecipeEdamam withIngredients(List<Ingredient>)
+ double getCalories()
+ void setCalories(double)
+ RecipeEdamam withCalories(double)
+ double getTotalWeight()
+ void setTotalWeight(double)
+ RecipeEdamam withTotalWeight(double)
+ double getTotalTime()
+ void setTotalTime(double)
+ RecipeEdamam withTotalTime(double)
+ List<String> getCuisineType()
+ void setCuisineType(List<String>)
+ RecipeEdamam withCuisineType(List<String>)
+ List<String> getMealType()
+ void setMealType(List<String>)
+ RecipeEdamam withMealType(List<String>)
+ List<String> getDishType()
+ void setDishType(List<String>)
+ RecipeEdamam withDishType(List<String>)
+ TotalNutrients getTotalNutrients()
+ void setTotalNutrients(TotalNutrients)
+ RecipeEdamam withTotalNutrients(TotalNutrients)
+ TotalDaily getTotalDaily()
+ void setTotalDaily(TotalDaily)
+ RecipeEdamam withTotalDaily(TotalDaily)
+ List<Digest> getDigest()
+ void setDigest(List<Digest>)
+ RecipeEdamam withDigest(List<Digest>)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ RecipeEdamam withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Zn__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Zn__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Zn__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Zn__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Zn__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Mg__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Mg__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Mg__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Mg__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Mg__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Tocpha {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Tocpha withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Tocpha withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Tocpha withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Tocpha withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.registration.Entity.User {
- int userid
- String username
- String address
- String password
+ int getUserid()
+ void setUserid(int)
+ String getUsername()
+ void setUsername(String)
+ String getAddress()
+ void setAddress(String)
+ String getPassword()
+ void setPassword(String)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitc__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitc__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitc__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitc__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitc__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipePersonalized.repository.AnalyseDietetique {
+ double quantityTotalRecipe(RecipePersonalized)
+ double quantityViandeRecipe(RecipePersonalized)
+ double quantityFruitsLegumesRecipe(RecipePersonalized)
+ double quantityFeculentsRecipe(RecipePersonalized)
+ double quantityProduitsLaitiersRecipe(RecipePersonalized)
+ double percentageCategory(double,double)
+ double quantityTotalRecipes(List<RecipePersonalized>)
+ double quantityViandeRecipes(List<RecipePersonalized>)
+ double quantityFruitsLegumesRecipes(List<RecipePersonalized>)
+ double quantityFeculentsRecipes(List<RecipePersonalized>)
+ double quantityProduitsLaitiersRecipes(List<RecipePersonalized>)
+ List<QuantityCat> analyseRecipe(RecipePersonalized)
+ List<QuantityCat> analyseRecipes(List<RecipePersonalized>)
+ void afficheAnalyse(List<String>)
+ List<String> recommandationRecipe(List<QuantityCat>)
+ List<String> recommandationRecipes(List<QuantityCat>)
}
class com.kenkogroup.kenko.recipe.entity.edamam.VitaRae__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ VitaRae__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ VitaRae__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ VitaRae__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ VitaRae__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitb12__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitb12__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitb12__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitb12__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitb12__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitd {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitd withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitd withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitd withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitd withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Example {
- String q
- long from
- long to
- boolean more
- long count
- List<Hit> hits
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getQ()
+ void setQ(String)
+ Example withQ(String)
+ long getFrom()
+ void setFrom(long)
+ Example withFrom(long)
+ long getTo()
+ void setTo(long)
+ Example withTo(long)
+ boolean isMore()
+ void setMore(boolean)
+ Example withMore(boolean)
+ long getCount()
+ void setCount(long)
+ Example withCount(long)
+ List<Hit> getHits()
+ void setHits(List<Hit>)
+ Example withHits(List<Hit>)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Example withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Ingredient {
- String text
- double quantity
- Object measure
- String food
- double weight
- String foodCategory
- String foodId
- String image
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getText()
+ void setText(String)
+ Ingredient withText(String)
+ double getQuantity()
+ void setQuantity(double)
+ Ingredient withQuantity(double)
+ Object getMeasure()
+ void setMeasure(Object)
+ Ingredient withMeasure(Object)
+ String getFood()
+ void setFood(String)
+ Ingredient withFood(String)
+ double getWeight()
+ void setWeight(double)
+ Ingredient withWeight(double)
+ String getFoodCategory()
+ void setFoodCategory(String)
+ Ingredient withFoodCategory(String)
+ String getFoodId()
+ void setFoodId(String)
+ Ingredient withFoodId(String)
+ String getImage()
+ void setImage(String)
+ Ingredient withImage(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Ingredient withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Chole__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Chole__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Chole__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Chole__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Chole__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.registration.Dto.UserDTO {
- int userid
- String username
- String address
- String password
+ int getUserid()
+ void setUserid(int)
+ String getUsername()
+ void setUsername(String)
+ String getAddress()
+ void setAddress(String)
+ String getPassword()
+ void setPassword(String)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Foldfe__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Foldfe__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Foldfe__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Foldfe__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Foldfe__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipePersonalized.entity.RecipePersonalized {
- int idRecipe
- String name
- int category
- List<Ingredient> ingredients
- String description
- int duration
- boolean taken
+ int getIdRecipe()
+ void setIdRecipe(int)
+ String getName()
+ void setName(String)
+ int getCategory()
+ void setCategory(int)
+ List<Ingredient> getIngredients()
+ void setIngredients(List<Ingredient>)
+ String getDescription()
+ void setDescription(String)
+ int getDuration()
+ void setDuration(int)
+ boolean isTaken()
+ void setTaken(boolean)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitb12 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitb12 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitb12 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitb12 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitb12 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.K__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ K__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ K__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ K__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ K__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.EnercKcal {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ EnercKcal withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ EnercKcal withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ EnercKcal withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ EnercKcal withAdditionalProperty(String,Object)
+ String toString()
}
interface com.kenkogroup.kenko.registration.Service.UserService {
~ String addUser(UserDTO)
}
class com.kenkogroup.kenko.recipePersonalized.service.RecipePersoService {
- BaseDonnee base
- AnalyseDietetique analyse
+ BaseDonnee getBase()
+ void setBase(BaseDonnee)
+ AnalyseDietetique getAnalyse()
+ void addRecipePerso(RecipePersonalized)
+ void updateRecipePerso(int,RecipePersonalized)
+ void deleteRecipePerso(int)
+ List<QuantityCat> analyseRecipePerso(RecipePersonalized)
+ List<QuantityCat> analyseRecipes(List<RecipePersonalized>)
+ List<String> recommandationRecipe(List<QuantityCat>)
+ List<String> recommandationRecipes(List<QuantityCat>)
}
class com.kenkogroup.kenko.recipePersonalized.repository.BaseDonnee {
- List<RecipePersonalized> recipes
- Map<Product,Double> products
+ List<RecipePersonalized> getRecipes()
+ void setRecipes(List<RecipePersonalized>)
+ Map<Product,Double> getProducts()
+ void setProducts(Map<Product,Double>)
+ void addRecipePerso(RecipePersonalized)
+ void updateRecipePerso(int,RecipePersonalized)
+ void deleteRecipePerso(int)
+ RecipePersonalized findRecipePersoById(int)
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fe__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fe__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fe__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fe__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fe__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Zn {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Zn withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Zn withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Zn withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Zn withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Ca {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Ca withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Ca withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Ca withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Ca withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Hit {
- RecipeEdamam recipe
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ RecipeEdamam getRecipe()
+ void setRecipe(RecipeEdamam)
+ Hit withRecipe(RecipeEdamam)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Hit withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fibtg__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fibtg__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fibtg__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fibtg__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fibtg__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.product.entity.Product {
- int id
~ String name
~ Category category
+ int getId()
+ void setId(int)
+ String getName()
+ void setName(String)
+ Category getCategory()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fat {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fat withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fat withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fat withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fat withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Nia {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Nia withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Nia withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Nia withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Nia withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Sub {
- String label
- String tag
- Object schemaOrgTag
- double total
- boolean hasRDI
- double daily
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Sub withLabel(String)
+ String getTag()
+ void setTag(String)
+ Sub withTag(String)
+ Object getSchemaOrgTag()
+ void setSchemaOrgTag(Object)
+ Sub withSchemaOrgTag(Object)
+ double getTotal()
+ void setTotal(double)
+ Sub withTotal(double)
+ boolean isHasRDI()
+ void setHasRDI(boolean)
+ Sub withHasRDI(boolean)
+ double getDaily()
+ void setDaily(double)
+ Sub withDaily(double)
+ String getUnit()
+ void setUnit(String)
+ Sub withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Sub withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.ingredient.entity.Ingredient {
- int idIngredient
~ Product product
~ Double quantity
+ Product getProduct()
+ void setProduct(Product)
+ Double getQuantity()
+ void setQuantity(Double)
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fat__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fat__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fat__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fat__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fat__1 withAdditionalProperty(String,Object)
+ String toString()
}
enum com.kenkogroup.kenko.category.entity.Meat {
+  FISH
+  CHICKEN
+  MEAT
- String name
+ String getName()
+ String analyse(Double)
}
class com.kenkogroup.kenko.category.entity.Category {
~ Meat meat
~ Vegetable vegetable
~ Other other
+ Meat getMeat()
+ Vegetable getVegetable()
+ Other getOther()
+ boolean isMeat()
+ boolean isVegetable()
+ boolean isOther()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Procnt__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Procnt__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Procnt__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Procnt__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Procnt__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fe {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fe withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fe withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fe withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fe withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Folfd {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Folfd withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Folfd withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Folfd withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Folfd withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Na__1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Na__1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Na__1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Na__1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Na__1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Digest {
- String label
- String tag
- Object schemaOrgTag
- double total
- boolean hasRDI
- double daily
- String unit
- List<Sub> sub
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Digest withLabel(String)
+ String getTag()
+ void setTag(String)
+ Digest withTag(String)
+ Object getSchemaOrgTag()
+ void setSchemaOrgTag(Object)
+ Digest withSchemaOrgTag(Object)
+ double getTotal()
+ void setTotal(double)
+ Digest withTotal(double)
+ boolean isHasRDI()
+ void setHasRDI(boolean)
+ Digest withHasRDI(boolean)
+ double getDaily()
+ void setDaily(double)
+ Digest withDaily(double)
+ String getUnit()
+ void setUnit(String)
+ Digest withUnit(String)
+ List<Sub> getSub()
+ void setSub(List<Sub>)
+ Digest withSub(List<Sub>)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Digest withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Sugar {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Sugar withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Sugar withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Sugar withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Sugar withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Folac {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Folac withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Folac withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Folac withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Folac withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Vitk1 {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Vitk1 withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Vitk1 withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Vitk1 withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Vitk1 withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.recipe.entity.edamam.Fasat {
- String label
- double quantity
- String unit
- Map<String,Object> additionalProperties
- {static} long serialVersionUID
+ String getLabel()
+ void setLabel(String)
+ Fasat withLabel(String)
+ double getQuantity()
+ void setQuantity(double)
+ Fasat withQuantity(double)
+ String getUnit()
+ void setUnit(String)
+ Fasat withUnit(String)
+ Map<String,Object> getAdditionalProperties()
+ void setAdditionalProperty(String,Object)
+ Fasat withAdditionalProperty(String,Object)
+ String toString()
}
class com.kenkogroup.kenko.registration.UserController.UserController {
- UserService userService
+ String saveUser(UserDTO)
}


java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.P__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fibtg
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Procnt
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Chole
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.TotalDaily
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Nia__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.K
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fams
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Tocpha__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.EnercKcal__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Na
com.kenkogroup.kenko.recipe.service.RecipeService <|.. com.kenkogroup.kenko.recipe.impl.RecipeServiceImpl
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.VitaRae
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitb6a
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fasat__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.SugarAlcohol
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.TotalNutrients
org.springframework.data.jpa.repository.JpaRepository <|-- com.kenkogroup.kenko.registration.Repo.UserRepo
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Chocdf
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fapu
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitb6a__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Mg
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.CHOCDFNet
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitd__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Thia
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Water
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Thia__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fatrn
com.kenkogroup.kenko.registration.Service.UserService <|.. com.kenkogroup.kenko.registration.Service.impl.UserIMPL
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Foldfe
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Chocdf__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Ribf
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.SUGARAdded
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitk1__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Ribf__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Ca__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitc
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.P
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.RecipeEdamam
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Zn__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Mg__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Tocpha
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitc__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.VitaRae__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitb12__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitd
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Example
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Ingredient
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Chole__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Foldfe__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitb12
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.K__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.EnercKcal
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fe__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Zn
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Ca
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Hit
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fibtg__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fat
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Nia
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Sub
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fat__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Procnt__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fe
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Folfd
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Na__1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Digest
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Sugar
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Folac
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Vitk1
java.io.Serializable <|.. com.kenkogroup.kenko.recipe.entity.edamam.Fasat
@enduml